const string SyberiaServer_ModPreffix = "[SYBERIA SERVER] ";
const bool SyberiaServer_DebugMode = true;

void SybLogSrv(string message)
{
	if (SyberiaServer_DebugMode) Print(SyberiaServer_ModPreffix + message);
}

// ADV MED
const float DIRTY_SYRINGE_BLOOD_INFECTION_CHANCE = 1.0; // 0.2

const float SEPSIS_STAGE1_TIME_SEC = 30;
const float SEPSIS_TEMPERATURE_MAX = 0.9;
const float SEPSIS_DEATH_TIME_SEC = 30;

const float PAIN_LVL1_TIME_SEC = 60 * 5;
const float PAIN_LVL2_TIME_SEC = 60 * 30;
const float PAIN_LVL3_TIME_SEC = 60 * 60;
const float PAIN_MAX_DURATION_SEC = 60 * 60 * 4;
const float PAINKILLER_MAX_DURATION_SEC = 60 * 60 * 1;

const float BLEEDING_BULLETHIT_HEALTHLOSE_PER_SECOND = -1;
const float BLEEDING_BULLETHIT_OPEN_PER_SECOND = -25;
const float BLEEDING_BULLETHIT_CUPD1_PER_SECOND = -10;
const float BLEEDING_BULLETHIT_CUPD2_PER_SECOND = -3;
const float BLEEDING_BULLETHIT_CUPD3_PER_SECOND = -1;

const float BLEEDING_KNIFEHIT_HEALTHLOSE_PER_SECOND = -1;
const float BLEEDING_KNIFEHIT_OPEN_PER_SECOND = -40;
const float BLEEDING_KNIFEHIT_CUPD1_PER_SECOND = -10;
const float BLEEDING_KNIFEHIT_CUPD2_PER_SECOND = -3;
const float BLEEDING_KNIFEHIT_CUPD3_PER_SECOND = -1;

const float BLEEDING_VISCERA_BLOODLOSE_PER_SECOND = -30;
const float BLEEDING_VISCERA_HEALTHLOSE_PER_SECOND = -5;

const float BLEEDING_HEMATOMA_BLOODLOSE_PER_SECOND = 0;
const float BLEEDING_HEMATOMA_HEALTHLOSE_PER_SECOND = -0.3;

const float HEMATOMA_REGEN_TIMER_SEC = 60 * 15;
const float CUTHIT_REGEN_TIMER_SEC = 60 * 5;

const float HEMOLOGIC_SHOCK_DIETIME_SEC = 60; 